### ISSUE TITLE
As a developer, I want to transform all the scripts to use controllers.

### ISSUE THREAD

**Issue by tchalvak** [BitLucid/ninjawars#332]
Pages that need controllers (not necessarily a complete list):

 - [ ] skills_mod.php
 - [x] stats.php
 - [x] village.php
 - [x] work.php
 - [ ] player.php
 - [x] shop.php
 - [x] shrine.php
 - [ ] inventory_mod.php
 - [ ] list.php
 - [x] login.php
 - [ ] logout.php
 - [x] messages.php
 - [ ] npc.php
 - [ ] dojo.php
 - [x] doshin_office.php
 - [x] enemies.php
 - [ ] events.php
 - [ ] index.php
 - [ ] attack_mod.php
 - [x] casino.php
 - [x] clan.php
 - [ ] confirm.php
 - [x] account.php
 - [ ] quests.php
 - [ ] rules.php
 - [ ] settings.php
 - [ ] signup.php
 - [ ] skills.php
 - [ ] splash.php
 - [ ] staff.php
 - [ ] static.php
 - [ ] tutorial.php
 - [ ] interview.php
 - [x] inventory.php
 - [x] list_all_players.php
 - [ ] main.php
 - [ ] map.php
 - [x] minichat.php
 - [ ] news.php
 - [x] npcs.php
 - [x] player_tags.php
 - [ ] public.php
 - [ ] 404.php
 - [ ] about.php
 - [ ] account_issues.php
 - [ ] api.php
 - [x] attack_npc.php
 - [x] attack_player.php
 - [x] chat.php
 - [ ] duel.php

**Comment by Beagle** [comment]
This isn't actionable as it stands because it's too large. I'm moving it to the backlog and we should open new issues for each of these items individually as we work on them.

**Comment by tchalvak** [comment]
I was just using this to get an overview of what was done.  Now that we can essentially count-down the files in /www/ to achieve the same effect, keeping this around is unnecessary.   (I probably shouldn't have named this issue with a user story, in the first place, was just momentum).
